import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppinsFont = Poppins({
  subsets: ["latin"],
  weight: "400",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppinsFont.className} antialiased bg-background `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
